import React from "react";
import "./components/TeamSelection.css";

export const Question = ({setCurrentPage, setPoints, level, category, currentTeam, points, setStatus}) => {
    const handleSetPage = (selectedPage) => {
        setCurrentPage(selectedPage);
    };

    const handleSetStatus = (newStatus) => {
        setStatus(newStatus);
    }

    const questions = [
        {
          id: 1,
          category: 'Geography',
          level: "easy",
          text: 'What is the capital of France?',
          options: ['Paris', 'Berlin', 'London', 'Madrid'],
          correctAnswer: 'Paris',
        },
        {
            id: 2,
            category: 'Science',
            level: "easy",
            text: 'What is the chemical symbol for water?',
            options: ['H2O', 'CO2', 'O2', 'N2'],
            correctAnswer: 'H2O',
          },
          {
            id: 3,
            category: 'Science',
            level: "easy",
            text: 'Which planet is known as the Red Planet?',
            options: ['Earth', 'Mars', 'Venus', 'Jupiter'],
            correctAnswer: 'Mars',
          },
          {
            id: 4,
            category: 'Science',
            level: "easy",
            text: 'What is the powerhouse of the cell?',
            options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Endoplasmic reticulum'],
            correctAnswer: 'Mitochondria',
          },
          {
            id: 5,
            category: 'Science',
            level: "easy",
            text: 'What is the largest mammal on Earth?',
            options: ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'],
            correctAnswer: 'Blue whale',
          },
          {
            id: 6,
            category: 'Science',
            level: "easy",
            text: 'Which gas do plants absorb from the atmosphere?',
            options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
            correctAnswer: 'Carbon dioxide',
          },
          {
            id: 7,
            category: 'Science',
            level: "easy",
            text: 'What is the Earth’s primary source of energy?',
            options: ['Wind', 'Coal', 'Sun', 'Natural gas'],
            correctAnswer: 'Sun',
          },
          {
            id: 8,
            category: 'Science',
            level: "easy",
            text: 'What is the smallest bone in the human body?',
            options: ['Femur', 'Radius', 'Cochlea', 'Tibia'],
            correctAnswer: 'Cochlea',
          },
          {
            id: 9,
            category: 'Science',
            level: "easy",
            text: 'Which gas do plants release during photosynthesis?',
            options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
            correctAnswer: 'Oxygen',
          },
          {
            id: 10,
            category: 'Science',
            level: "medium",
            text: 'What is the chemical symbol for gold?',
            options: ['Au', 'Ag', 'Cu', 'Fe'],
            correctAnswer: 'Au',
          },
          {
            id: 11,
            category: 'Science',
            level: "medium",
            text: 'Which planet is known as the "Morning Star" or "Evening Star"?',
            options: ['Mercury', 'Venus', 'Mars', 'Jupiter'],
            correctAnswer: 'Venus',
          },
          {
            id: 12,
            category: 'Science',
            level: "medium",
            text: 'What is the process by which plants make their own food?',
            options: ['Photosynthesis', 'Respiration', 'Transpiration', 'Fermentation'],
            correctAnswer: 'Photosynthesis',
          },
          {
            id: 13,
            category: 'Science',
            level: "medium",
            text: 'Which element is essential for the formation of bones in the human body?',
            options: ['Calcium', 'Iron', 'Sodium', 'Potassium'],
            correctAnswer: 'Calcium',
          },
          {
            id: 14,
            category: 'Science',
            level: "medium",
            text: 'What is the freezing point of water in Celsius?',
            options: ['-10°C', '0°C', '10°C', '20°C'],
            correctAnswer: '0°C',
          },
          {
            id: 15,
            category: 'Science',
            level: "medium",
            text: 'Which force holds the nucleus of an atom together?',
            options: ['Electromagnetic force', 'Gravity', 'Nuclear force', 'Friction'],
            correctAnswer: 'Nuclear force',
          },
          {
            id: 16,
            category: 'Science',
            level: "medium",
            text: 'What is the largest organ in the human body?',
            options: ['Heart', 'Lungs', 'Skin', 'Liver'],
            correctAnswer: 'Skin',
          },
          {
            id: 17,
            category: 'Science',
            level: "medium",
            text: 'What is the chemical symbol for oxygen?',
            options: ['O2', 'O', 'CO2', 'H2O'],
            correctAnswer: 'O2',
          },
          {
            id: 18,
            category: 'Science',
            level: "hard",
            text: 'What is the speed of light in a vacuum?',
            options: ['299,792 km/s', '150,000 km/s', '449,234 km/s', '200,000 km/s'],
            correctAnswer: '299,792 km/s',
          },
          {
            id: 19,
            category: 'Science',
            level: "hard",
            text: 'In chemistry, what does the term "pH" measure?',
            options: ['Pressure of Hydrogen', 'Potential of Hydrogen', 'Purity of Hydrocarbons', 'Power of Heat'],
            correctAnswer: 'Potential of Hydrogen',
          },
          {
            id: 20,
            category: 'Science',
            level: "hard",
            text: 'What is the smallest particle of an element that retains its chemical properties?',
            options: ['Atom', 'Molecule', 'Cell', 'Electron'],
            correctAnswer: 'Atom',
          },
          {
            id: 21,
            category: 'Science',
            level: "hard",
            text: 'Who developed the theory of general relativity?',
            options: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Galileo Galilei'],
            correctAnswer: 'Albert Einstein',
          },
          {
            id: 22,
            category: 'Science',
            level: "hard",
            text: 'What is the unit of electrical resistance?',
            options: ['Ohm', 'Ampere', 'Volt', 'Watt'],
            correctAnswer: 'Ohm',
          },
          {
            id: 23,
            category: 'Science',
            level: "hard",
            text: 'Which gas makes up the majority of the Earth\'s atmosphere?',
            options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
            correctAnswer: 'Nitrogen',
          },
          {
            id: 24,
            category: 'Science',
            level: "hard",
            text: 'What is the process by which a cell divides into two daughter cells?',
            options: ['Mitosis', 'Meiosis', 'Fission', 'Budding'],
            correctAnswer: 'Mitosis',
          },
          {
            id: 25,
            category: 'Science',
            level: "hard",
            text: 'What is the temperature at which all molecular motion ceases?',
            options: ['-273.15°C', '-200°C', '-100°C', '0°C'],
            correctAnswer: '-273.15°C',
          },
          {
            id: 26,
            category: 'Pop Culture',
            level: "easy",
            text: 'Who is known as the "King of Pop"?',
            options: ['Elvis Presley', 'Michael Jackson', 'Justin Bieber', 'Madonna'],
            correctAnswer: 'Michael Jackson',
          },
          {
            id: 27,
            category: 'Pop Culture',
            level: "easy",
            text: 'Which animated film features a character named Simba?',
            options: ['Shrek', 'The Lion King', 'Finding Nemo', 'Toy Story'],
            correctAnswer: 'The Lion King',
          },
          {
            id: 28,
            category: 'Pop Culture',
            level: "easy",
            text: 'What is the name of Harry Potter\'s owl?',
            options: ['Hedwig', 'Errol', 'Scabbers', 'Crookshanks'],
            correctAnswer: 'Hedwig',
          },
          {
            id: 29,
            category: 'Pop Culture',
            level: "easy",
            text: 'Which superhero is known for his web-slinging abilities?',
            options: ['Superman', 'Batman', 'Spider-Man', 'Iron Man'],
            correctAnswer: 'Spider-Man',
          },
          {
            id: 30,
            category: 'Pop Culture',
            level: "easy",
            text: 'What is the name of the famous wizarding school in the Harry Potter series?',
            options: ['Hogwarts', 'Beauxbatons', 'Durmstrang', 'Ilvermorny'],
            correctAnswer: 'Hogwarts',
          },
          {
            id: 31,
            category: 'Pop Culture',
            level: "easy",
            text: 'Which Disney princess has a magic golden flower?',
            options: ['Cinderella', 'Rapunzel', 'Ariel', 'Belle'],
            correctAnswer: 'Rapunzel',
          },
          {
            id: 32,
            category: 'Pop Culture',
            level: "easy",
            text: 'Who played the character Jack Dawson in the movie Titanic?',
            options: ['Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise'],
            correctAnswer: 'Leonardo DiCaprio',
          },
          {
            id: 33,
            category: 'Pop Culture',
            level: "easy",
            text: 'Which TV series features characters named Ross, Rachel, and Chandler?',
            options: ['Friends', 'The Office', 'Breaking Bad', 'Stranger Things'],
            correctAnswer: 'Friends',
          },
          {
            id: 34,
            category: 'Pop Culture',
            level: "medium",
            text: 'Which iconic movie features a character named Don Vito Corleone?',
            options: ['The Godfather', 'Pulp Fiction', 'Scarface', 'Goodfellas'],
            correctAnswer: 'The Godfather',
          },
          {
            id: 35,
            category: 'Pop Culture',
            level: "medium",
            text: 'In which year did the first episode of "Game of Thrones" air?',
            options: ['2008', '2010', '2011', '2013'],
            correctAnswer: '2011',
          },
          {
            id: 36,
            category: 'Pop Culture',
            level: "medium",
            text: 'What is the name of the fictional African country in the movie "Black Panther"?',
            options: ['Wakanda', 'Zamunda', 'Genovia', 'Elbonia'],
            correctAnswer: 'Wakanda',
          },
          {
            id: 37,
            category: 'Pop Culture',
            level: "medium",
            text: 'Who is the lead singer of the band Queen?',
            options: ['Freddie Mercury', 'David Bowie', 'Elton John', 'Mick Jagger'],
            correctAnswer: 'Freddie Mercury',
          },
          {
            id: 38,
            category: 'Pop Culture',
            level: "medium",
            text: 'What is the name of the fictional wizarding sport played on broomsticks in Harry Potter?',
            options: ['Broom Ball', 'Quidditch', 'Witchball', 'Magic Soccer'],
            correctAnswer: 'Quidditch',
          },
          {
            id: 39,
            category: 'Pop Culture',
            level: "medium",
            text: 'Who wrote the play "Romeo and Juliet"?',
            options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
            correctAnswer: 'William Shakespeare',
          },
          {
            id: 40,
            category: 'Pop Culture',
            level: "medium",
            text: 'What is the name of the fictional wizarding school in the "Harry Potter" series?',
            options: ['Hogwarts', 'Beauxbatons', 'Durmstrang', 'Ilvermorny'],
            correctAnswer: 'Hogwarts',
          },
          {
            id: 41,
            category: 'Pop Culture',
            level: "medium",
            text: 'Which animated film features a character named Elsa with ice powers?',
            options: ['Moana', 'Frozen', 'Tangled', 'Brave'],
            correctAnswer: 'Frozen',
          },
          {
            id: 42,
            category: 'Pop Culture',
            level: "medium",
            text: 'Which actor played the character Tony Stark/Iron Man in the Marvel Cinematic Universe?',
            options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
            correctAnswer: 'Robert Downey Jr.',
          },
          {
            id: 43,
            category: 'Pop Culture',
            level: "hard",
            text: 'In the TV series "Breaking Bad," what is the street name of Walter White’s blue meth?',
            options: ['Blue Ice', 'Crystal Clear', 'Blue Sky', 'Meth Blue'],
            correctAnswer: 'Blue Sky',
          },
          {
            id: 44,
            category: 'Pop Culture',
            level: "hard",
            text: 'Who wrote the dystopian novel "1984"?',
            options: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'],
            correctAnswer: 'George Orwell',
          },
          {
            id: 45,
            category: 'Pop Culture',
            level: "hard",
            text: 'Which animated film features the character Buzz Lightyear?',
            options: ['Toy Story', 'Finding Nemo', 'Shrek', 'The Lion King'],
            correctAnswer: 'Toy Story',
          },
          {
            id: 46,
            category: 'Pop Culture',
            level: "hard",
            text: 'In the film "The Matrix," what is the real name of the character Neo?',
            options: ['John Anderson', 'Thomas Anderson', 'Jack Thompson', 'Michael Williams'],
            correctAnswer: 'Thomas Anderson',
          },
          {
            id: 47,
            category: 'Pop Culture',
            level: "hard",
            text: 'Who directed the 1994 film "Pulp Fiction"?',
            options: ['Steven Spielberg', 'Martin Scorsese', 'Quentin Tarantino', 'Christopher Nolan'],
            correctAnswer: 'Quentin Tarantino',
          },
          {
            id: 48,
            category: 'Pop Culture',
            level: "hard",
            text: 'What is the name of the fictional newspaper in the "Harry Potter" series?',
            options: ['The Daily Bugle', 'The Daily Prophet', 'The Quibbler', 'The Times'],
            correctAnswer: 'The Daily Prophet',
          },
          {
            id: 49,
            category: 'Pop Culture',
            level: "hard",
            text: 'Which character says the famous line "Here’s looking at you, kid" in the film "Casablanca"?',
            options: ['Humphrey Bogart', 'Ingrid Bergman', 'Claude Rains', 'Paul Henreid'],
            correctAnswer: 'Humphrey Bogart',
          },
          {
            id: 50,
            category: 'History',
            level: 'Easy',
            text: 'Who was the first President of the United States?',
            options: ['John Adams', 'Thomas Jefferson', 'George Washington', 'James Madison'],
            correctAnswer: 'George Washington',
          },
          {
            id: 51,
            category: 'History',
            level: 'Easy',
            text: 'In what year did Christopher Columbus first reach the Americas?',
            options: ['1492', '1607', '1776', '1498'],
            correctAnswer: '1492',
          },
          {
            id: 52,
            category: 'History',
            level: 'Easy',
            text: 'Which ancient civilization built the pyramids?',
            options: ['Maya', 'Inca', 'Egyptian', 'Greek'],
            correctAnswer: 'Egyptian',
          },
          {
            id: 53,
            category: 'History',
            level: 'Easy',
            text: 'Who was the legendary queen of ancient Egypt?',
            options: ['Cleopatra', 'Nefertiti', 'Hatshepsut', 'Isis'],
            correctAnswer: 'Cleopatra',
          },
          {
            id: 54,
            category: 'History',
            level: 'Easy',
            text: 'What event marked the start of World War I?',
            options: ['Assassination of Archduke', 'Signing Treaty of Versailles', 'Battle of Stalingrad', 'D-Day'],
            correctAnswer: 'Assassination of Archduke',
          },
          {
            id: 55,
            category: 'History',
            level: 'Easy',
            text: 'Who wrote the "I Have a Dream" speech?',
            options: ['Malcolm X', 'Martin Luther King Jr.', 'Nelson Mandela', 'Barack Obama'],
            correctAnswer: 'Martin Luther King Jr.',
          },
          {
            id: 56,
            category: 'History',
            level: 'Easy',
            text: 'Which civilization built the Great Wall of China?',
            options: ['Mongol Empire', 'Qin Dynasty', 'Han Dynasty', 'Tang Dynasty'],
            correctAnswer: 'Qin Dynasty',
          },
          {
            id: 57,
            category: 'History',
            level: 'Easy',
            text: 'Who was the leader of the Soviet Union during World War II?',
            options: ['Joseph Stalin', 'Vladimir Putin', 'Leon Trotsky', 'Nikita Khrushchev'],
            correctAnswer: 'Joseph Stalin',
          },
          {
            id: 58,
            category: 'History',
            level: 'Medium',
            text: 'Which war was fought between the North and South regions of the United States?',
            options: ['American Revolution', 'Civil War', 'World War I', 'Vietnam War'],
            correctAnswer: 'Civil War',
          },
          {
            id: 59,
            category: 'History',
            level: 'Medium',
            text: 'Who was the first Emperor of China?',
            options: ['Emperor Qin Shi Huang', 'Emperor Han Wudi', 'Emperor Tang Taizong', 'Emperor Ming Yongle'],
            correctAnswer: 'Emperor Qin Shi Huang',
          },
          {
            id: 60,
            category: 'History',
            level: 'Medium',
            text: 'What event is known as the "Night of Broken Glass," a violent anti-Jewish pogrom?',
            options: ['Kristallnacht', 'The Great Purge', 'The Cultural Revolution', 'The Spanish Inquisition'],
            correctAnswer: 'Kristallnacht',
          },
          {
            id: 61,
            category: 'History',
            level: 'Medium',
            text: 'Which ancient civilization created the first known system of writing, known as cuneiform?',
            options: ['Sumerians', 'Ancient Egyptians', 'Greeks', 'Romans'],
            correctAnswer: 'Sumerians',
          },
          {
            id: 62,
            category: 'History',
            level: 'Medium',
            text: 'Who was the founder of the Mongol Empire?',
            options: ['Genghis Khan', 'Kublai Khan', 'Attila the Hun', 'Alexander the Great'],
            correctAnswer: 'Genghis Khan',
          },
          {
            id: 63,
            category: 'History',
            level: 'Medium',
            text: 'Which battle is considered the turning point of the Pacific War during World War II?',
            options: ['Battle of Midway', 'Battle of Okinawa', 'Battle of Iwo Jima', 'Pearl Harbor'],
            correctAnswer: 'Battle of Midway',
          },
          {
            id: 64,
            category: 'History',
            level: 'Medium',
            text: 'Who was the first woman to win a Nobel Prize?',
            options: ['Marie Curie', 'Rosalind Franklin', 'Ada Lovelace', 'Jane Goodall'],
            correctAnswer: 'Marie Curie',
          },
          {
            id: 65,
            category: 'History',
            level: 'Medium',
            text: 'What political ideology was associated with Karl Marx and Friedrich Engels?',
            options: ['Capitalism', 'Socialism', 'Communism', 'Fascism'],
            correctAnswer: 'Communism',
          },
          {
            id: 66,
            category: 'History',
            level: 'Hard',
            text: 'Who was the first Roman Emperor?',
            options: ['Julius Caesar', 'Augustus', 'Nero', 'Caligula'],
            correctAnswer: 'Augustus',
          },
          {
            id: 67,
            category: 'History',
            level: 'Hard',
            text: 'What ancient city was known as the "City of a Thousand Minarets"?',
            options: ['Baghdad', 'Cairo', 'Istanbul', 'Mecca'],
            correctAnswer: 'Cairo',
          },
          {
            id: 68,
            category: 'History',
            level: 'Hard',
            text: 'Which empire was ruled by Emperor Justinian I in the 6th century AD?',
            options: ['Ottoman Empire', 'Byzantine Empire', 'Roman Empire', 'Mongol Empire'],
            correctAnswer: 'Byzantine Empire',
          },
          {
            id: 69,
            category: 'History',
            level: 'Hard',
            text: 'Who was the last Tsar of Russia before the Russian Revolution?',
            options: ['Nicholas II', 'Alexander II', 'Ivan the Terrible', 'Peter the Great'],
            correctAnswer: 'Nicholas II',
          },
          {
            id: 70,
            category: 'History',
            level: 'Hard',
            text: 'Which ancient civilization built the city of Carthage in North Africa?',
            options: ['Greeks', 'Romans', 'Phoenicians', 'Persians'],
            correctAnswer: 'Phoenicians',
          },
          {
            id: 71,
            category: 'History',
            level: 'Hard',
            text: 'In which year did the Spanish Armada attempt to invade England?',
            options: ['1588', '1620', '1492', '1642'],
            correctAnswer: '1588',
          },
          {
            id: 72,
            category: 'History',
            level: 'Hard',
            text: 'What ancient wonder was located in the city of Babylon?',
            options: ['Hanging Gardens', 'Colossus of Rhodes', 'Pyramids of Giza', 'Temple of Artemis'],
            correctAnswer: 'Hanging Gardens',
          },
          {
            id: 73,
            category: 'History',
            level: 'Hard',
            text: 'Which Chinese philosopher is known for his teachings on ethics and morality?',
            options: ['Confucius', 'Laozi', 'Sun Tzu', 'Mencius'],
            correctAnswer: 'Confucius',
          },
          {
            id: 82,
            category: 'Technology',
            level: 'Medium',
            text: 'Which programming language is known for its use in data analysis and machine learning?',
            options: ['Java', 'Python', 'C#', 'Ruby'],
            correctAnswer: 'Python',
          },
          {
            id: 83,
            category: 'Technology',
            level: 'Medium',
            text: 'What does the acronym "VPN" stand for?',
            options: ['Virtual Private Network', 'Very Private Network', 'Visual Processing Node', 'Vivid Public Network'],
            correctAnswer: 'Virtual Private Network',
          },
          {
            id: 84,
            category: 'Technology',
            level: 'Medium',
            text: 'Who is often referred to as the co-founder of Microsoft?',
            options: ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Larry Page'],
            correctAnswer: 'Bill Gates',
          },
          {
            id: 85,
            category: 'Technology',
            level: 'Medium',
            text: 'What is the purpose of an operating system?',
            options: ['Manage hardware resources', 'Create graphical designs', 'Run computer games', 'Browse the internet'],
            correctAnswer: 'Manage hardware resources',
          },
          {
            id: 86,
            category: 'Technology',
            level: 'Medium',
            text: 'Which social media platform is known for its character limit on posts?',
            options: ['Facebook', 'Instagram', 'Twitter', 'LinkedIn'],
            correctAnswer: 'Twitter',
          },
          {
            id: 87,
            category: 'Technology',
            level: 'Medium',
            text: 'In computer terms, what does "GUI" stand for?',
            options: ['Graphical User Interface', 'General User Interaction', 'Global User Integration', 'Guided User Interface'],
            correctAnswer: 'Graphical User Interface',
          },
          {
            id: 88,
            category: 'Technology',
            level: 'Medium',
            text: 'Which company is known for its gaming console series, PlayStation?',
            options: ['Microsoft', 'Nintendo', 'Sony', 'Sega'],
            correctAnswer: 'Sony',
          },
          {
            id: 89,
            category: 'Technology',
            level: 'Medium',
            text: 'What is the purpose of the HTML "DOCTYPE" declaration?',
            options: ['Define document type and version', 'Insert new HTML tag', 'Specify document structure', 'Add document title'],
            correctAnswer: 'Define document type and version',
          },
          {
            id: 90,
            category: 'Technology',
            level: 'Hard',
            text: 'What is the primary purpose of the programming language Assembly?',
            options: ['Web development', 'System-level programming', 'Data analysis', 'Game design'],
            correctAnswer: 'System-level programming',
          },
          {
            id: 91,
            category: 'Technology',
            level: 'Hard',
            text: 'Which cryptographic algorithm is commonly used for secure communication over the internet?',
            options: ['RSA', 'AES', 'MD5', 'SHA-1'],
            correctAnswer: 'RSA',
          },
          {
            id: 92,
            category: 'Technology',
            level: 'Hard',
            text: 'What is the concept of "big data" associated with?',
            options: ['Large file storage', 'Massive data analysis', 'Complex algorithms', 'High-speed internet'],
            correctAnswer: 'Massive data analysis',
          },
          {
            id: 93,
            category: 'Technology',
            level: 'Hard',
            text: 'Which programming paradigm focuses on the declarative specification of how a program should accomplish a task?',
            options: ['Object-oriented programming', 'Imperative programming', 'Functional programming', 'Procedural programming'],
            correctAnswer: 'Functional programming',
          },
          {
            id: 94,
            category: 'Technology',
            level: 'Hard',
            text: 'In computer security, what does the term "firewall" refer to?',
            options: ['Software for video editing', 'Barrier in data centers', 'Network security device', 'Compression algorithm'],
            correctAnswer: 'Network security device',
          },
          {
            id: 95,
            category: 'Technology',
            level: 'Hard',
            text: 'What is the primary function of the protocol HTTPS?',
            options: ['Email communication', 'Secure file transfer', 'Web page encryption', 'Database management'],
            correctAnswer: 'Web page encryption',
          },
          {
            id: 96,
            category: 'Technology',
            level: 'Hard',
            text: 'Which algorithm is commonly used for artificial neural networks and deep learning?',
            options: ['K-means', 'Random Forest', 'Backpropagation', 'Apriori'],
            correctAnswer: 'Backpropagation',
          },
          {
            id: 97,
            category: 'Technology',
            level: 'Hard',
            text: 'What does the term "blockchain" refer to in the context of technology?',
            options: ['Encrypted email communication', 'Distributed ledger for transactions', 'Cloud-based storage', 'Virtual reality simulations'],
            correctAnswer: 'Distributed ledger for transactions',
          },
          {
            id: 100,
            category: 'Art',
            level: 'Easy',
            text: 'Who painted the Mona Lisa?',
            options: ['Vincent van Gogh', 'Leonardo da Vinci', 'Pablo Picasso', 'Claude Monet'],
            correctAnswer: 'Leonardo da Vinci',
          },
          {
            id: 101,
            category: 'Art',
            level: 'Easy',
            text: 'Which artist is known for his impressionist paintings of water lilies?',
            options: ['Edgar Degas', 'Claude Monet', 'Vincent van Gogh', 'Pierre-Auguste Renoir'],
            correctAnswer: 'Claude Monet',
          },
          {
            id: 102,
            category: 'Art',
            level: 'Easy',
            text: 'Who created the famous sculpture of David?',
            options: ['Michelangelo', 'Donatello', 'Leonardo da Vinci', 'Raphael'],
            correctAnswer: 'Michelangelo',
          },
          {
            id: 103,
            category: 'Art',
            level: 'Easy',
            text: 'Which artist is associated with the melting clocks in the painting "The Persistence of Memory"?',
            options: ['Salvador Dalí', 'Pablo Picasso', 'Jackson Pollock', 'Georgia O\'Keeffe'],
            correctAnswer: 'Salvador Dalí',
          },
          {
            id: 104,
            category: 'Art',
            level: 'Easy',
            text: 'Who is known for creating large, colorful, and abstract paintings like "Number 5, 1948"?',
            options: ['Jackson Pollock', 'Mark Rothko', 'Willem de Kooning', 'Andy Warhol'],
            correctAnswer: 'Jackson Pollock',
          },
          {
            id: 105,
            category: 'Art',
            level: 'Easy',
            text: 'Which artist is famous for painting sunflowers?',
            options: ['Vincent van Gogh', 'Claude Monet', 'Pablo Picasso', 'Georgia O\'Keeffe'],
            correctAnswer: 'Vincent van Gogh',
          },
          {
            id: 106,
            category: 'Art',
            level: 'Easy',
            text: 'Who is known for his paintings of "soup cans"?',
            options: ['Vincent van Gogh', 'Leonardo da Vinci', 'Pablo Picasso', 'Andy Warhol'],
            correctAnswer: 'Andy Warhol',
          },
          {
            id: 107,
            category: 'Art',
            level: 'Easy',
            text: 'Which artist is famous for her self-portraits, often depicting her distinctive unibrow?',
            options: ['Frida Kahlo', 'Georgia O\'Keeffe', 'Tamara de Lempicka', 'Yayoi Kusama'],
            correctAnswer: 'Frida Kahlo',
          },
          {
            id: 108,
            category: 'Art',
            level: 'Medium',
            text: 'Who painted "The Starry Night"?',
            options: ['Vincent van Gogh', 'Claude Monet', 'Pablo Picasso', 'Edvard Munch'],
            correctAnswer: 'Vincent van Gogh',
          },
          {
            id: 109,
            category: 'Art',
            level: 'Medium',
            text: 'Which artist is known for creating "The Scream"?',
            options: ['Edvard Munch', 'Salvador Dalí', 'Pablo Picasso', 'Claude Monet'],
            correctAnswer: 'Edvard Munch',
          },
          {
            id: 110,
            category: 'Art',
            level: 'Medium',
            text: 'Who sculpted the statue of David in Florence, Italy?',
            options: ['Michelangelo', 'Donatello', 'Leonardo da Vinci', 'Raphael'],
            correctAnswer: 'Michelangelo',
          },
          {
            id: 111,
            category: 'Art',
            level: 'Medium',
            text: 'Which art movement is characterized by geometric shapes and primary colors?',
            options: ['Cubism', 'Abstract Expressionism', 'Pop Art', 'Surrealism'],
            correctAnswer: 'Cubism',
          },
          {
            id: 112,
            category: 'Art',
            level: 'Medium',
            text: 'Who is known for his paintings of ballet dancers and horse races?',
            options: ['Edgar Degas', 'Claude Monet', 'Vincent van Gogh', 'Pierre-Auguste Renoir'],
            correctAnswer: 'Edgar Degas',
          },
          {
            id: 113,
            category: 'Art',
            level: 'Medium',
            text: 'Which artist is associated with the art movement called "The Blue Rider"?',
            options: ['Wassily Kandinsky', 'Piet Mondrian', 'Marc Chagall', 'Georgia O\'Keeffe'],
            correctAnswer: 'Wassily Kandinsky',
          },
          {
            id: 114,
            category: 'Art',
            level: 'Medium',
            text: 'Who painted "Guernica," a powerful anti-war mural?',
            options: ['Pablo Picasso', 'Salvador Dalí', 'Frida Kahlo', 'Joan Miró'],
            correctAnswer: 'Pablo Picasso',
          },
          {
            id: 115,
            category: 'Art',
            level: 'Medium',
            text: 'Which artist is known for his mobile sculptures that move with air currents?',
            options: ['Alexander Calder', 'Jean-Michel Basquiat', 'Keith Haring', 'Yves Klein'],
            correctAnswer: 'Alexander Calder',
          },
          {
            id: 116,
            category: 'Art',
            level: 'Hard',
            text: 'Who painted "Les Demoiselles d\'Avignon," a groundbreaking work in the development of Cubism?',
            options: ['Pablo Picasso', 'Georges Braque', 'Fernand Léger', 'Juan Gris'],
            correctAnswer: 'Pablo Picasso',
          },
          {
            id: 117,
            category: 'Art',
            level: 'Hard',
            text: 'Which artist is known for his "readymades," ordinary objects presented as works of art?',
            options: ['Marcel Duchamp', 'René Magritte', 'Man Ray', 'Yves Tanguy'],
            correctAnswer: 'Marcel Duchamp',
          },
          {
            id: 118,
            category: 'Art',
            level: 'Hard',
            text: 'Who created the large-scale environmental artwork "The Lightning Field"?',
            options: ['James Turrell', 'Christo and Jeanne-Claude', 'Richard Serra', 'Maya Lin'],
            correctAnswer: 'Walter De Maria',
          },
          {
            id: 119,
            category: 'Art',
            level: 'Hard',
            text: 'Which artist is associated with the photorealist painting style?',
            options: ['Chuck Close', 'Richard Estes', 'Audrey Flack', 'Robert Bechtle'],
            correctAnswer: 'Chuck Close',
          },
          {
            id: 120,
            category: 'Art',
            level: 'Hard',
            text: 'Who designed the iconic glass pyramid at the Louvre Museum in Paris?',
            options: ['I. M. Pei', 'Frank Gehry', 'Norman Foster', 'Zaha Hadid'],
            correctAnswer: 'I. M. Pei',
          },
          {
            id: 121,
            category: 'Art',
            level: 'Hard',
            text: 'Which artist created the series "The Gates" in New York City\'s Central Park?',
            options: ['Christo and Jeanne-Claude', 'Anish Kapoor', 'Yayoi Kusama', 'Damien Hirst'],
            correctAnswer: 'Christo and Jeanne-Claude',
          },
          {
            id: 122,
            category: 'Art',
            level: 'Hard',
            text: 'Who painted the famous mural "Man at the Crossroads" at Rockefeller Center?',
            options: ['Diego Rivera', 'David Alfaro Siqueiros', 'José Clemente Orozco', 'Frida Kahlo'],
            correctAnswer: 'Diego Rivera',
          },
          {
            id: 123,
            category: 'Art',
            level: 'Hard',
            text: 'Which artist is known for his large-scale outdoor sculptures like "Balloon Flower"?',
            options: ['Jeff Koons', 'Antony Gormley', 'Anish Kapoor', 'Damien Hirst'],
            correctAnswer: 'Jeff Koons',
          },
          {
            id: 124,
            category: 'Sports',
            level: 'Easy',
            text: 'In which sport does a pitcher throw a ball to a batter?',
            options: ['Baseball', 'Football', 'Basketball', 'Soccer'],
            correctAnswer: 'Baseball',
          },
          {
            id: 125,
            category: 'Sports',
            level: 'Easy',
            text: 'What is the object of the game in basketball?',
            options: ['Score most points', 'Kick ball into goal', 'Hit shuttlecock over net', 'Knock down all pins'],
            correctAnswer: 'Score most points',
          },
          {
            id: 126,
            category: 'Sports',
            level: 'Easy',
            text: 'Which sport is played on a rectangular field with a goal at each end?',
            options: ['Soccer', 'Hockey', 'Tennis', 'Golf'],
            correctAnswer: 'Soccer',
          },
          {
            id: 127,
            category: 'Sports',
            level: 'Easy',
            text: 'What is the primary objective in golf?',
            options: ['Hit longest drive', 'Sink ball in fewest strokes', 'Score most points', 'Serve an ace'],
            correctAnswer: 'Sink ball in fewest strokes',
          },
          {
            id: 128,
            category: 'Sports',
            level: 'Easy',
            text: 'In which sport might you perform a slam dunk?',
            options: ['Basketball', 'Tennis', 'Volleyball', 'Gymnastics'],
            correctAnswer: 'Basketball',
          },
          {
            id: 129,
            category: 'Sports',
            level: 'Easy',
            text: 'What is the primary objective in baseball? To score the most: ',
            options: ['Touchdowns', 'Runs', 'Goals', 'Points'],
            correctAnswer: 'Runs',
          },
          {
            id: 130,
            category: 'Sports',
            level: 'Easy',
            text: 'In which sport might you see a home run?',
            options: ['Cricket', 'Soccer', 'Baseball', 'Rugby'],
            correctAnswer: 'Baseball',
          },
          {
            id: 131,
            category: 'Sports',
            level: 'Easy',
            text: 'What is the term for a perfect score in bowling?',
            options: ['Strike', 'Spare', 'Turkey', 'Homerun'],
            correctAnswer: 'Strike',
          },
          {
            id: 132,
            category: 'Sports',
            level: 'Medium',
            text: 'Which country won the FIFA World Cup in 2018?',
            options: ['Germany', 'Brazil', 'France', 'Argentina'],
            correctAnswer: 'France',
          },
          {
            id: 133,
            category: 'Sports',
            level: 'Medium',
            text: 'Who holds the record for the most Olympic gold medals in athletics?',
            options: ['Carl Lewis', 'Usain Bolt', 'Jesse Owens', 'Michael Phelps'],
            correctAnswer: 'Usain Bolt',
          },
          {
            id: 134,
            category: 'Sports',
            level: 'Medium',
            text: 'What is the national sport of Japan?',
            options: ['Sumo wrestling', 'Judo', 'Karate', 'Kendo'],
            correctAnswer: 'Sumo wrestling',
          },
          {
            id: 135,
            category: 'Sports',
            level: 'Medium',
            text: 'Who is known as "The Greatest" in boxing?',
            options: ['Mike Tyson', 'Muhammad Ali', 'Floyd Mayweather', 'Manny Pacquiao'],
            correctAnswer: 'Muhammad Ali',
          },
          {
            id: 136,
            category: 'Sports',
            level: 'Medium',
            text: 'Which tennis player has won the most Grand Slam singles titles?',
            options: ['Serena Williams', 'Rafael Nadal', 'Roger Federer', 'Novak Djokovic'],
            correctAnswer: 'Margaret Court',
          },
          {
            id: 137,
            category: 'Sports',
            level: 'Medium',
            text: 'In which year did the first modern Olympic Games take place?',
            options: ['1886', '1900', '1896', '1912'],
            correctAnswer: '1896',
          },
          {
            id: 138,
            category: 'Sports',
            level: 'Medium',
            text: 'Which NFL team has won the most Super Bowls?',
            options: ['Pittsburgh Steelers', 'Dallas Cowboys', 'New England Patriots', 'Green Bay Packers'],
            correctAnswer: 'New England Patriots',
          },
          {
            id: 139,
            category: 'Sports',
            level: 'Medium',
            text: 'Who won the Tour de France a record seven consecutive times?',
            options: ['Lance Armstrong', 'Chris Froome', 'Eddy Merckx', 'Miguel Indurain'],
            correctAnswer: 'Lance Armstrong',
          },
          {
            id: 140,
            category: 'Sports',
            level: 'Hard',
            text: 'Which country hosted the Summer Olympics in 2008?',
            options: ['United States', 'United Kingdom', 'China', 'Brazil'],
            correctAnswer: 'China',
          },
          {
            id: 141,
            category: 'Sports',
            level: 'Hard',
            text: 'Who is the only boxer to finish his career undefeated in both amateur and professional boxing?',
            options: ['Muhammad Ali', 'Floyd Mayweather', 'Joe Louis', 'Rocky Marciano'],
            correctAnswer: 'Floyd Mayweather',
          },
          {
            id: 142,
            category: 'Sports',
            level: 'Hard',
            text: 'In which year did the first official cricket Test match take place?',
            options: ['1865', '1877', '1892', '1901'],
            correctAnswer: '1877',
          },
          {
            id: 143,
            category: 'Sports',
            level: 'Hard',
            text: 'Who holds the record for the most career goals in men\'s international football?',
            options: ['Lionel Messi', 'Cristiano Ronaldo', 'Pele', 'Diego Maradona'],
            correctAnswer: 'Cristiano Ronaldo',
          },
          {
            id: 144,
            category: 'Sports',
            level: 'Hard',
            text: 'Which country has won the most gold medals in the Winter Olympics?',
            options: ['Norway', 'United States', 'Germany', 'Russia'],
            correctAnswer: 'Norway',
          },
          {
            id: 145,
            category: 'Sports',
            level: 'Hard',
            text: 'Who is the only athlete to have won Olympic gold medals in both the 100m and 200m sprints in three consecutive Olympics?',
            options: ['Usain Bolt', 'Carl Lewis', 'Jesse Owens', 'Florence Griffith-Joyner'],
            correctAnswer: 'Usain Bolt',
          },
          {
            id: 146,
            category: 'Sports',
            level: 'Hard',
            text: 'Which boxer is known as "The Real Deal"?',
            options: ['Mike Tyson', 'Evander Holyfield', 'Lennox Lewis', 'George Foreman'],
            correctAnswer: 'Evander Holyfield',
          },
          {
            id: 147,
            category: 'Sports',
            level: 'Hard',
            text: 'In which year did the first Wimbledon tennis championship take place?',
            options: ['1877', '1892', '1901', '1910'],
            correctAnswer: '1877',
          },
          {
            id: 150,
            category: 'Geography',
            level: 'Easy',
            text: 'What is the capital of France?',
            options: ['Paris', 'Berlin', 'London', 'Madrid'],
            correctAnswer: 'Paris',
          },
          {
            id: 151,
            category: 'Geography',
            level: 'Easy',
            text: 'Which river is the longest in the world?',
            options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
            correctAnswer: 'Nile',
          },
          {
            id: 152,
            category: 'Geography',
            level: 'Easy',
            text: 'In which continent is the Sahara Desert located?',
            options: ['Africa', 'Asia', 'South America', 'Australia'],
            correctAnswer: 'Africa',
          },
          {
            id: 153,
            category: 'Geography',
            level: 'Easy',
            text: 'What is the largest ocean on Earth?',
            options: ['Atlantic Ocean', 'Indian Ocean', 'Southern Ocean', 'Pacific Ocean'],
            correctAnswer: 'Pacific Ocean',
          },
          {
            id: 154,
            category: 'Geography',
            level: 'Easy',
            text: 'Which country is known as the Land of the Rising Sun?',
            options: ['China', 'South Korea', 'Japan', 'Vietnam'],
            correctAnswer: 'Japan',
          },
          {
            id: 155,
            category: 'Geography',
            level: 'Easy',
            text: 'What is the capital of Australia?',
            options: ['Sydney', 'Canberra', 'Melbourne', 'Brisbane'],
            correctAnswer: 'Canberra',
          },
          {
            id: 156,
            category: 'Geography',
            level: 'Easy',
            text: 'Which mountain is the highest in the world?',
            options: ['K2', 'Mount Everest', 'Kangchenjunga', 'Lhotse'],
            correctAnswer: 'Mount Everest',
          },
          {
            id: 157,
            category: 'Geography',
            level: 'Easy',
            text: 'Which canal connects the Mediterranean Sea to the Red Sea?',
            options: ['Suez Canal', 'Panama Canal', 'Erie Canal', 'Grand Canal'],
            correctAnswer: 'Suez Canal',
          },
          {
            id: 158,
            category: 'Geography',
            level: 'Medium',
            text: 'Which two countries share the longest international border?',
            options: ['Canada, USA', 'Russia, China', 'India, Pakistan', 'Brazil, Argentina'],
            correctAnswer: 'Canada, USA',
          },
          {
            id: 159,
            category: 'Geography',
            level: 'Medium',
            text: 'What is the capital of Canada?',
            options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
            correctAnswer: 'Ottawa',
          },
          {
            id: 160,
            category: 'Geography',
            level: 'Medium',
            text: 'Which African country is known as the "Pearl of Africa"?',
            options: ['Nigeria', 'Kenya', 'Uganda', 'South Africa'],
            correctAnswer: 'Uganda',
          },
          {
            id: 161,
            category: 'Geography',
            level: 'Medium',
            text: 'In which ocean are the Maldives located?',
            options: ['Indian Ocean', 'Atlantic Ocean', 'Pacific Ocean', 'Arctic Ocean'],
            correctAnswer: 'Indian Ocean',
          },
          {
            id: 162,
            category: 'Geography',
            level: 'Medium',
            text: 'Which river is the longest in South America?',
            options: ['Amazon River', 'Paraná River', 'Orinoco River', 'Magdalena River'],
            correctAnswer: 'Amazon River',
          },
          {
            id: 163,
            category: 'Geography',
            level: 'Medium',
            text: 'What is the capital of South Korea?',
            options: ['Seoul', 'Tokyo', 'Beijing', 'Bangkok'],
            correctAnswer: 'Seoul',
          },
          {
            id: 164,
            category: 'Geography',
            level: 'Medium',
            text: 'Which desert is the largest in the world?',
            options: ['Gobi Desert', 'Sahara Desert', 'Arabian Desert', 'Karakum Desert'],
            correctAnswer: 'Sahara Desert',
          },
          {
            id: 165,
            category: 'Geography',
            level: 'Medium',
            text: 'What is the capital of Argentina?',
            options: ['Buenos Aires', 'Rio de Janeiro', 'Santiago', 'Lima'],
            correctAnswer: 'Buenos Aires',
          },
          {
            id: 166,
            category: 'Geography',
            level: 'Hard',
            text: 'Which two countries are separated by the Durand Line?',
            options: ['Pakistan, India', 'Afghanistan, Iran', 'India, China', 'Russia, Kazakhstan'],
            correctAnswer: 'Afghanistan, Pakistan',
          },
          {
            id: 167,
            category: 'Geography',
            level: 'Hard',
            text: 'What is the smallest independent country in the world?',
            options: ['Monaco', 'San Marino', 'Vatican City', 'Liechtenstein'],
            correctAnswer: 'Vatican City',
          },
          {
            id: 168,
            category: 'Geography',
            level: 'Hard',
            text: 'Which African country is known as the "Land of a Thousand Hills"?',
            options: ['Kenya', 'Tanzania', 'Rwanda', 'Uganda'],
            correctAnswer: 'Rwanda',
          },
          {
            id: 169,
            category: 'Geography',
            level: 'Hard',
            text: 'In which mountain range is Mount Everest located?',
            options: ['Rocky Mountains', 'Himalayas', 'Andes', 'Alps'],
            correctAnswer: 'Himalayas',
          },
          {
            id: 170,
            category: 'Geography',
            level: 'Hard',
            text: 'What is the capital of Kazakhstan?',
            options: ['Astana', 'Almaty', 'Nur-Sultan', 'Bishkek'],
            correctAnswer: 'Nur-Sultan',
          },
          {
            id: 171,
            category: 'Geography',
            level: 'Hard',
            text: 'Which river is the longest in the world?',
            options: ['Amazon', 'Nile', 'Yangtze', 'Congo'],
            correctAnswer: 'Nile',
          },
          {
            id: 172,
            category: 'Geography',
            level: 'Hard',
            text: 'What is the capital of Mongolia?',
            options: ['Ulaanbaatar', 'Astana', 'Bishkek', 'Dushanbe'],
            correctAnswer: 'Ulaanbaatar',
          },
          {
            id: 173,
            category: 'Geography',
            level: 'Hard',
            text: 'Which lake is the largest by surface area in Africa?',
            options: ['Victoria', 'Tanganyika', 'Malawi', 'Turkana'],
            correctAnswer: 'Victoria',
          },
          {
            id: 174,
            category: 'Cuisine',
            level: 'Easy',
            text: 'What is the main ingredient in guacamole?',
            options: ['Tomatoes', 'Avocado', 'Onions', 'Lime'],
            correctAnswer: 'Avocado',
          },
          {
            id: 175,
            category: 'Cuisine',
            level: 'Easy',
            text: 'Which country is famous for sushi?',
            options: ['Italy', 'China', 'Japan', 'India'],
            correctAnswer: 'Japan',
          },
          {
            id: 176,
            category: 'Cuisine',
            level: 'Easy',
            text: 'What is the traditional bread in France?',
            options: ['Ciabatta', 'Baguette', 'Pita', 'Sourdough'],
            correctAnswer: 'Baguette',
          },
          {
            id: 177,
            category: 'Cuisine',
            level: 'Easy',
            text: 'What is the main ingredient in hummus?',
            options: ['Chickpeas', 'Lentils', 'Black beans', 'Kidney beans'],
            correctAnswer: 'Chickpeas',
          },
          {
            id: 178,
            category: 'Cuisine',
            level: 'Easy',
            text: 'Which spice gives Indian curry its yellow color?',
            options: ['Turmeric', 'Cumin', 'Coriander', 'Cardamom'],
            correctAnswer: 'Turmeric',
          },
          {
            id: 179,
            category: 'Cuisine',
            level: 'Easy',
            text: 'What is the traditional pasta of Italy?',
            options: ['Macaroni', 'Spaghetti', 'Fettuccine', 'Farfalle'],
            correctAnswer: 'Spaghetti',
          },
          {
            id: 180,
            category: 'Cuisine',
            level: 'Easy',
            text: 'In which country did the sandwich originate?',
            options: ['France', 'Italy', 'England', 'Germany'],
            correctAnswer: 'England',
          },
          {
            id: 181,
            category: 'Cuisine',
            level: 'Easy',
            text: 'What is the primary ingredient in paella?',
            options: ['Rice', 'Noodles', 'Quinoa', 'Barley'],
            correctAnswer: 'Rice',
          },
          {
            id: 182,
            category: 'Cuisine',
            level: 'Medium',
            text: 'Which country is known for its spicy cuisine, including dishes like kimchi and bulgogi?',
            options: ['Japan', 'China', 'India', 'South Korea'],
            correctAnswer: 'South Korea',
          },
          {
            id: 183,
            category: 'Cuisine',
            level: 'Medium',
            text: 'What is the traditional Mexican dish consisting of a folded or rolled tortilla filled with various ingredients?',
            options: ['Tostada', 'Enchilada', 'Burrito', 'Quesadilla'],
            correctAnswer: 'Burrito',
          },
          {
            id: 184,
            category: 'Cuisine',
            level: 'Medium',
            text: 'Which Italian dish is a rice dish typically cooked in broth to a creamy consistency?',
            options: ['Lasagna', 'Risotto', 'Gnocchi', 'Cannelloni'],
            correctAnswer: 'Risotto',
          },
          {
            id: 185,
            category: 'Cuisine',
            level: 'Medium',
            text: 'In which country did the sandwich originate?',
            options: ['France', 'Italy', 'England', 'Germany'],
            correctAnswer: 'England',
          },
          {
            id: 186,
            category: 'Cuisine',
            level: 'Medium',
            text: 'What is the main ingredient in the Middle Eastern dish falafel?',
            options: ['Chickpeas', 'Lentils', 'Black beans', 'Kidney beans'],
            correctAnswer: 'Chickpeas',
          },
          {
            id: 187,
            category: 'Cuisine',
            level: 'Medium',
            text: 'Which spice is often used in both sweet and savory dishes and comes from the bark of a tree?',
            options: ['Cinnamon', 'Paprika', 'Cumin', 'Cardamom'],
            correctAnswer: 'Cinnamon',
          },
          {
            id: 188,
            category: 'Cuisine',
            level: 'Medium',
            text: 'What is the traditional Scottish dish made of minced meat and oatmeal?',
            options: ['Haggis', 'Black Pudding', 'Scotch Pie', 'Stovies'],
            correctAnswer: 'Haggis',
          },
          {
            id: 189,
            category: 'Cuisine',
            level: 'Medium',
            text: 'Which Asian cuisine is known for its use of raw fish and vinegared rice?',
            options: ['Thai', 'Chinese', 'Japanese', 'Indian'],
            correctAnswer: 'Japanese',
          },
          {
            id: 190,
            category: 'Cuisine',
            level: 'Hard',
            text: 'What is the traditional fermented beverage made from rice in Japanese cuisine?',
            options: ['Sake', 'Soju', 'Umeshu', 'Makgeolli'],
            correctAnswer: 'Sake',
          },
          {
            id: 191,
            category: 'Cuisine',
            level: 'Hard',
            text: 'In which country did the dish "Peking duck" originate?',
            options: ['Japan', 'China', 'South Korea', 'Vietnam'],
            correctAnswer: 'China',
          },
          {
            id: 192,
            category: 'Cuisine',
            level: 'Hard',
            text: 'What is the name of the traditional Mexican soup made with tripe and chili peppers?',
            options: ['Menudo', 'Pozole', 'Sopa de Lima', 'Caldo Tlalpeño'],
            correctAnswer: 'Menudo',
          },
          {
            id: 193,
            category: 'Cuisine',
            level: 'Hard',
            text: 'Which spice, derived from the flower buds of a tree, is one of the most expensive spices in the world?',
            options: ['Saffron', 'Cardamom', 'Vanilla', 'Star Anise'],
            correctAnswer: 'Saffron',
          },
          {
            id: 194,
            category: 'Cuisine',
            level: 'Hard',
            text: 'What is the primary ingredient in the Indian dish "Saag Paneer"?',
            options: ['Lamb', 'Chicken', 'Paneer', 'Tofu'],
            correctAnswer: 'Paneer',
          },
          {
            id: 195,
            category: 'Cuisine',
            level: 'Hard',
            text: 'Which French dish consists of a round, flat pastry with sweet or savory toppings?',
            options: ['Croissant', 'Quiche', 'Baguette', 'Crêpe'],
            correctAnswer: 'Crêpe',
          },
          {
            id: 196,
            category: 'Cuisine',
            level: 'Hard',
            text: 'What is the traditional Ethiopian flatbread made from fermented teff flour?',
            options: ['Injera', 'Naan', 'Matzo', 'Pita'],
            correctAnswer: 'Injera',
          },
          {
            id: 197,
            category: 'Cuisine',
            level: 'Hard',
            text: 'Which Southeast Asian fruit, known for its strong odor, is often banned in hotels and public transportation?',
            options: ['Durian', 'Mangosteen', 'Rambutan', 'Dragon Fruit'],
            correctAnswer: 'Durian',
          },
          {
            id: 200,
            category: 'Literature',
            level: 'Easy',
            text: 'Who is the author of "Romeo and Juliet"?',
            options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
            correctAnswer: 'William Shakespeare',
          },
          {
            id: 201,
            category: 'Literature',
            level: 'Easy',
            text: 'What is the setting of the novel "To Kill a Mockingbird"?',
            options: ['Maycomb', 'London', 'New York', 'Paris'],
            correctAnswer: 'Maycomb',
          },
          {
            id: 202,
            category: 'Literature',
            level: 'Easy',
            text: 'In which play does the character Hamlet appear?',
            options: ['Macbeth', 'Othello', 'Hamlet', 'King Lear'],
            correctAnswer: 'Hamlet',
          },
          {
            id: 203,
            category: 'Literature',
            level: 'Easy',
            text: 'What is the first book in J.K. Rowling\'s "Harry Potter" series?',
            options: ['The Goblet of Fire', 'The Prisoner of Azkaban', 'The Sorceror\'s Stone', 'The Chamber of Secrets'],
            correctAnswer: 'The Sorceror\'s Stone',
          },
          {
            id: 204,
            category: 'Literature',
            level: 'Easy',
            text: 'Who wrote the play "Macbeth"?',
            options: ['William Shakespeare', 'Jane Austen', 'Charles Dickens', 'F. Scott Fitzgerald'],
            correctAnswer: 'William Shakespeare',
          },
          {
            id: 205,
            category: 'Literature',
            level: 'Easy',
            text: 'What is the name of the hobbit protagonist in J.R.R. Tolkien\'s "The Lord of the Rings"?',
            options: ['Frodo Baggins', 'Samwise Gamgee', 'Bilbo Baggins', 'Gandalf'],
            correctAnswer: 'Frodo Baggins',
          },
          {
            id: 206,
            category: 'Literature',
            level: 'Easy',
            text: 'Who is the author of "Pride and Prejudice"?',
            options: ['Jane Austen', 'Charlotte Brontë', 'Emily Brontë', 'Charles Dickens'],
            correctAnswer: 'Jane Austen',
          },
          {
            id: 207,
            category: 'Literature',
            level: 'Easy',
            text: 'What is the title of the first book in the "Hunger Games" series?',
            options: ['Catching Fire', 'Mockingjay', 'The Hunger Games', 'Divergent'],
            correctAnswer: 'The Hunger Games',
          },
          {
            id: 208,
            category: 'Literature',
            level: 'Medium',
            text: 'Who wrote the tragedy "King Lear"?',
            options: ['William Shakespeare', 'Homer', 'Anton Chekhov', 'Fyodor Dostoevsky'],
            correctAnswer: 'William Shakespeare',
          },
          {
            id: 209,
            category: 'Literature',
            level: 'Medium',
            text: 'In George Orwell\'s "Animal Farm," what type of animal is Napoleon?',
            options: ['Horse', 'Pig', 'Chicken', 'Dog'],
            correctAnswer: 'Pig',
          },
          {
            id: 210,
            category: 'Literature',
            level: 'Medium',
            text: 'Who wrote the novel "Jane Eyre"?',
            options: ['Charlotte Brontë', 'Emily Brontë', 'Jane Austen', 'Charles Dickens'],
            correctAnswer: 'Charlotte Brontë',
          },
          {
            id: 211,
            category: 'Literature',
            level: 'Medium',
            text: 'What is the central theme of Franz Kafka\'s "The Metamorphosis"?',
            options: ['Love and Betrayal', 'Identity and Alienation', 'War and Peace', 'Good vs. Evil'],
            correctAnswer: 'Identity and Alienation',
          },
          {
            id: 212,
            category: 'Literature',
            level: 'Medium',
            text: 'Who is the protagonist in Mary Shelley\'s "Frankenstein"?',
            options: ['Victor Frankenstein', 'The Creature', 'Henry Clerval', 'Elizabeth Lavenza'],
            correctAnswer: 'Victor Frankenstein',
          },
          {
            id: 213,
            category: 'Literature',
            level: 'Medium',
            text: 'What is the title of F. Scott Fitzgerald\'s most famous novel?',
            options: ['The Great Gatsby', 'To Kill a Mockingbird', '1984', 'Brave New World'],
            correctAnswer: 'The Great Gatsby',
          },
          {
            id: 214,
            category: 'Literature',
            level: 'Medium',
            text: 'In "The Catcher in the Rye," what is the name of Holden Caulfield\'s younger sister?',
            options: ['Phoebe', 'Jane', 'Sally', 'Allie'],
            correctAnswer: 'Phoebe',
          },
          {
            id: 215,
            category: 'Literature',
            level: 'Medium',
            text: 'Which Shakespeare play features the character Iago?',
            options: ['Macbeth', 'Othello', 'Hamlet', 'King Lear'],
            correctAnswer: 'Othello',
          },
          {
            id: 216,
            category: 'Literature',
            level: 'Hard',
            text: 'In James Joyce\'s "Ulysses," what is the name of the protagonist?',
            options: ['Leopold Bloom', 'Stephen Dedalus', 'Molly Bloom', 'Gabriel Conroy'],
            correctAnswer: 'Leopold Bloom',
          },
          {
            id: 217,
            category: 'Literature',
            level: 'Hard',
            text: 'Who wrote the epic poem "Paradise Lost"?',
            options: ['John Milton', 'Homer', 'Dante Alighieri', 'Virgil'],
            correctAnswer: 'John Milton',
          },
          {
            id: 218,
            category: 'Literature',
            level: 'Hard',
            text: 'Which novel opens with "All happy families are alike; each unhappy family is unhappy in its own way."?',
            options: [
              'Moby Dick', 'Anna Karenina', 'War and Peace', 'Madame Bovary',
            ],
            correctAnswer: 'Anna Karenina',
          },
          {
            id: 219,
            category: 'Literature',
            level: 'Hard',
            text: 'Which Irish author wrote "The Picture of Dorian Gray"?',
            options: ['Oscar Wilde', 'James Joyce', 'George Bernard Shaw', 'Bram Stoker'],
            correctAnswer: 'Oscar Wilde',
          },
          {
            id: 220,
            category: 'Literature',
            level: 'Hard',
            text: 'Who is the author of the novel "One Hundred Years of Solitude"?',
            options: ['Gabriel García Márquez', 'Isabel Allende', 'Mario Vargas Llosa', 'Julio Cortázar'],
            correctAnswer: 'Gabriel García Márquez',
          },
          {
            id: 221,
            category: 'Literature',
            level: 'Hard',
            text: 'In Dante Alighieri\'s "Divine Comedy," what is the name of the protagonist?',
            options: ['Dante', 'Virgil', 'Beatrice', 'Ciacco'],
            correctAnswer: 'Dante',
          },
          {
            id: 222,
            category: 'Literature',
            level: 'Hard',
            text: 'Who wrote the play "Long Day\'s Journey into Night"?',
            options: ['Eugene O\'Neill', 'Arthur Miller', 'Tennessee Williams', 'Samuel Beckett'],
            correctAnswer: 'Eugene O\'Neill',
          },
          {
            id: 223,
            category: 'Literature',
            level: 'Hard',
            text: 'What is the real name of the author George Orwell?',
            options: ['Eric Blair', 'George Eliot', 'Charles Dickens', 'Jane Austen'],
            correctAnswer: 'Eric Blair',
          },
          {
            id: 224,
            category: 'Movies & TV',
            level: 'Easy',
            text: 'What is the name of the wizard in "The Lord of the Rings" who guides the Fellowship?',
            options: ['Gandalf', 'Saruman', 'Radagast', 'Frodo'],
            correctAnswer: 'Gandalf',
          },
          {
            id: 225,
            category: 'Movies & TV',
            level: 'Easy',
            text: 'Who played the character Jack Dawson in the movie "Titanic"?',
            options: ['Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise'],
            correctAnswer: 'Leonardo DiCaprio',
          },
          {
            id: 226,
            category: 'Movies & TV',
            level: 'Easy',
            text: 'In "Friends," what is the name of Ross and Monica\'s sister?',
            options: ['Phoebe', 'Rachel', 'Janice', 'Amy'],
            correctAnswer: 'Amy',
          },
          {
            id: 227,
            category: 'Movies & TV',
            level: 'Easy',
            text: 'Which animated film features a character named Simba?',
            options: ['Shrek', 'The Lion King', 'Finding Nemo', 'Toy Story'],
            correctAnswer: 'The Lion King',
          },
          {
            id: 228,
            category: 'Movies & TV',
            level: 'Easy',
            text: 'What is the name of Harry Potter\'s owl?',
            options: ['Hedwig', 'Errol', 'Scabbers', 'Crookshanks'],
            correctAnswer: 'Hedwig',
          },
          {
            id: 229,
            category: 'Movies & TV',
            level: 'Easy',
            text: 'Who is known as the "King of Pop"?',
            options: ['Elvis Presley', 'Michael Jackson', 'Justin Bieber', 'Madonna'],
            correctAnswer: 'Michael Jackson',
          },
          {
            id: 230,
            category: 'Movies & TV',
            level: 'Easy',
            text: 'Which superhero is known for his web-slinging abilities?',
            options: ['Superman', 'Batman', 'Spider-Man', 'Iron Man'],
            correctAnswer: 'Spider-Man',
          },
          {
            id: 231,
            category: 'Movies & TV',
            level: 'Easy',
            text: 'What is the name of the fictional African country in the movie "Black Panther"?',
            options: ['Wakanda', 'Zamunda', 'Genovia', 'Elbonia'],
            correctAnswer: 'Wakanda',
          },
          {
            id: 232,
            category: 'Movies & TV',
            level: 'Medium',
            text: 'Who played the character Tony Stark/Iron Man in the Marvel Cinematic Universe?',
            options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
            correctAnswer: 'Robert Downey Jr.',
          },
          {
            id: 233,
            category: 'Movies & TV',
            level: 'Medium',
            text: 'In the TV series "Breaking Bad," what is the street name of Walter White’s blue meth?',
            options: ['Blue Ice', 'Crystal Clear', 'Blue Sky', 'Meth Blue'],
            correctAnswer: 'Blue Sky',
          },
          {
            id: 234,
            category: 'Movies & TV',
            level: 'Medium',
            text: 'Who wrote the dystopian novel "1984"?',
            options: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'],
            correctAnswer: 'George Orwell',
          },
          {
            id: 235,
            category: 'Movies & TV',
            level: 'Medium',
            text: 'Which TV series features characters named Ross, Rachel, and Chandler?',
            options: ['Friends', 'The Office', 'Breaking Bad', 'Stranger Things'],
            correctAnswer: 'Friends',
          },
          {
            id: 236,
            category: 'Movies & TV',
            level: 'Medium',
            text: 'Who directed the 1994 film "Pulp Fiction"?',
            options: ['Steven Spielberg', 'Martin Scorsese', 'Quentin Tarantino', 'Christopher Nolan'],
            correctAnswer: 'Quentin Tarantino',
          },
          {
            id: 237,
            category: 'Movies & TV',
            level: 'Medium',
            text: 'What is the name of the fictional newspaper in the "Harry Potter" series?',
            options: ['The Daily Bugle', 'The Daily Prophet', 'The Quibbler', 'The Times'],
            correctAnswer: 'The Daily Prophet',
          },
          {
            id: 238,
            category: 'Movies & TV',
            level: 'Medium',
            text: 'Which character says the famous line "Here’s looking at you, kid" in the film "Casablanca"?',
            options: ['Humphrey Bogart', 'Ingrid Bergman', 'Claude Rains', 'Paul Henreid'],
            correctAnswer: 'Humphrey Bogart',
          },
          {
            id: 239,
            category: 'Movies & TV',
            level: 'Medium',
            text: 'In the film "The Matrix," what is the real name of the character Neo?',
            options: ['John Anderson', 'Thomas Anderson', 'Jack Thompson', 'Michael Williams'],
            correctAnswer: 'Thomas Anderson',
          },
          {
            id: 240,
            category: 'Movies & TV',
            level: 'Hard',
            text: 'Which actor played the character Tony Stark/Iron Man in the Marvel Cinematic Universe?',
            options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
            correctAnswer: 'Robert Downey Jr.',
          },
          {
            id: 241,
            category: 'Movies & TV',
            level: 'Hard',
            text: 'In the TV series "Breaking Bad," what is the street name of Walter White’s blue meth?',
            options: ['Blue Ice', 'Crystal Clear', 'Blue Sky', 'Meth Blue'],
            correctAnswer: 'Blue Sky',
          },
          {
            id: 242,
            category: 'Movies & TV',
            level: 'Hard',
            text: 'Who wrote the dystopian novel "1984"?',
            options: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'],
            correctAnswer: 'George Orwell',
          },
          {
            id: 243,
            category: 'Movies & TV',
            level: 'Hard',
            text: 'Which TV series features characters named Ross, Rachel, and Chandler?',
            options: ['Friends', 'The Office', 'Breaking Bad', 'Stranger Things'],
            correctAnswer: 'Friends',
          },
          {
            id: 244,
            category: 'Movies & TV',
            level: 'Hard',
            text: 'Who directed the 1994 film "Pulp Fiction"?',
            options: ['Steven Spielberg', 'Martin Scorsese', 'Quentin Tarantino', 'Christopher Nolan'],
            correctAnswer: 'Quentin Tarantino',
          },
          {
            id: 245,
            category: 'Movies & TV',
            level: 'Hard',
            text: 'What is the name of the fictional newspaper in the "Harry Potter" series?',
            options: ['The Daily Bugle', 'The Daily Prophet', 'The Quibbler', 'The Times'],
            correctAnswer: 'The Daily Prophet',
          },
          {
            id: 246,
            category: 'Movies & TV',
            level: 'Hard',
            text: 'Which character says the famous line "Here’s looking at you, kid" in the film "Casablanca"?',
            options: ['Humphrey Bogart', 'Ingrid Bergman', 'Claude Rains', 'Paul Henreid'],
            correctAnswer: 'Humphrey Bogart',
          },
          {
            id: 247,
            category: 'Movies & TV',
            level: 'Hard',
            text: 'In the film "The Matrix," what is the real name of the character Neo?',
            options: ['John Anderson', 'Thomas Anderson', 'Jack Thompson', 'Michael Williams'],
            correctAnswer: 'Thomas Anderson',
          },
          {
            id: 248,
            category: 'Music',
            level: 'Easy',
            text: 'Who is known as the "King of Pop"?',
            options: ['Elvis Presley', 'Michael Jackson', 'Justin Bieber', 'Madonna'],
            correctAnswer: 'Michael Jackson',
          },
          {
            id: 249,
            category: 'Music',
            level: 'Easy',
            text: 'What is the name of Harry Potter\'s owl?',
            options: ['Hedwig', 'Errol', 'Scabbers', 'Crookshanks'],
            correctAnswer: 'Hedwig',
          },
          {
            id: 250,
            category: 'Music',
            level: 'Easy',
            text: 'Which superhero is known for his web-slinging abilities?',
            options: ['Superman', 'Batman', 'Spider-Man', 'Iron Man'],
            correctAnswer: 'Spider-Man',
          },
          {
            id: 251,
            category: 'Music',
            level: 'Easy',
            text: 'Who played the character Jack Dawson in the movie Titanic?',
            options: ['Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise'],
            correctAnswer: 'Leonardo DiCaprio',
          },
          {
            id: 252,
            category: 'Music',
            level: 'Easy',
            text: 'Which Disney princess has a magic golden flower?',
            options: ['Cinderella', 'Rapunzel', 'Ariel', 'Belle'],
            correctAnswer: 'Rapunzel',
          },
          {
            id: 253,
            category: 'Music',
            level: 'Easy',
            text: 'What is the name of the fictional African country in the movie "Black Panther"?',
            options: ['Wakanda', 'Zamunda', 'Genovia', 'Elbonia'],
            correctAnswer: 'Wakanda',
          },
          {
            id: 254,
            category: 'Music',
            level: 'Easy',
            text: 'Who is the lead singer of the band Queen?',
            options: ['Freddie Mercury', 'David Bowie', 'Elton John', 'Mick Jagger'],
            correctAnswer: 'Freddie Mercury',
          },
          {
            id: 255,
            category: 'Music',
            level: 'Easy',
            text: 'What is the name of the fictional wizarding sport played on broomsticks in Harry Potter?',
            options: ['Broom Ball', 'Quidditch', 'Witchball', 'Magic Soccer'],
            correctAnswer: 'Quidditch',
          },
          {
            id: 256,
            category: 'Music',
            level: 'Medium',
            text: 'Which animated film features a character named Elsa with ice powers?',
            options: ['Moana', 'Frozen', 'Tangled', 'Brave'],
            correctAnswer: 'Frozen',
          },
          {
            id: 257,
            category: 'Music',
            level: 'Medium',
            text: 'Which actor played the character Tony Stark/Iron Man in the Marvel Cinematic Universe?',
            options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
            correctAnswer: 'Robert Downey Jr.',
          },
          {
            id: 258,
            category: 'Music',
            level: 'Medium',
            text: 'In the TV series "Breaking Bad," what is the street name of Walter White’s blue meth?',
            options: ['Blue Ice', 'Crystal Clear', 'Blue Sky', 'Meth Blue'],
            correctAnswer: 'Blue Sky',
          },
          {
            id: 259,
            category: 'Music',
            level: 'Medium',
            text: 'Who wrote the dystopian novel "1984"?',
            options: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'],
            correctAnswer: 'George Orwell',
          },
          {
            id: 260,
            category: 'Music',
            level: 'Medium',
            text: 'Which character says the famous line "Here’s looking at you, kid" in the film "Casablanca"?',
            options: ['Humphrey Bogart', 'Ingrid Bergman', 'Claude Rains', 'Paul Henreid'],
            correctAnswer: 'Humphrey Bogart',
          },
          {
            id: 261,
            category: 'Music',
            level: 'Medium',
            text: 'What is the name of the fictional newspaper in the "Harry Potter" series?',
            options: ['The Daily Bugle', 'The Daily Prophet', 'The Quibbler', 'The Times'],
            correctAnswer: 'The Daily Prophet',
          },
          {
            id: 262,
            category: 'Music',
            level: 'Medium',
            text: 'Who directed the 1994 film "Pulp Fiction"?',
            options: ['Steven Spielberg', 'Martin Scorsese', 'Quentin Tarantino', 'Christopher Nolan'],
            correctAnswer: 'Quentin Tarantino',
          },
          {
            id: 263,
            category: 'Music',
            level: 'Medium',
            text: 'In the film "The Matrix," what is the real name of the character Neo?',
            options: ['John Anderson', 'Thomas Anderson', 'Jack Thompson', 'Michael Williams'],
            correctAnswer: 'Thomas Anderson',
          },
          {
            id: 264,
            category: 'Music',
            level: 'Hard',
            text: 'Who wrote the play "Romeo and Juliet"?',
            options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
            correctAnswer: 'William Shakespeare',
          },
          {
            id: 265,
            category: 'Music',
            level: 'Hard',
            text: 'What is the name of the fictional wizarding sport played on broomsticks in Harry Potter?',
            options: ['Broom Ball', 'Quidditch', 'Witchball', 'Magic Soccer'],
            correctAnswer: 'Quidditch',
          },
          {
            id: 266,
            category: 'Music',
            level: 'Hard',
            text: 'What is the name of the fictional wizarding school in the "Harry Potter" series?',
            options: ['Hogwarts', 'Beauxbatons', 'Durmstrang', 'Ilvermorny'],
            correctAnswer: 'Hogwarts',
          },
          {
            id: 267,
            category: 'Music',
            level: 'Hard',
            text: 'Which animated film features a character named Elsa with ice powers?',
            options: ['Moana', 'Frozen', 'Tangled', 'Brave'],
            correctAnswer: 'Frozen',
          },
          {
            id: 268,
            category: 'Music',
            level: 'Hard',
            text: 'Which actor played the character Tony Stark/Iron Man in the Marvel Cinematic Universe?',
            options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
            correctAnswer: 'Robert Downey Jr.',
          },
          {
            id: 269,
            category: 'Music',
            level: 'Hard',
            text: 'In the TV series "Breaking Bad," what is the street name of Walter White’s blue meth?',
            options: ['Blue Ice', 'Crystal Clear', 'Blue Sky', 'Meth Blue'],
            correctAnswer: 'Blue Sky',
          },
          {
            id: 270,
            category: 'Music',
            level: 'Hard',
            text: 'Who wrote the dystopian novel "1984"?',
            options: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'],
            correctAnswer: 'George Orwell',
          },
          {
            id: 271,
            category: 'Music',
            level: 'Hard',
            text: 'Which character says the famous line "Here’s looking at you, kid" in the film "Casablanca"?',
            options: ['Humphrey Bogart', 'Ingrid Bergman', 'Claude Rains', 'Paul Henreid'],
            correctAnswer: 'Humphrey Bogart',
          },
          {
            id: 272,
            category: 'General Trivia',
            level: 'Easy',
            text: 'Which planet is known as the Red Planet?',
            options: ['Earth', 'Mars', 'Venus', 'Jupiter'],
            correctAnswer: 'Mars',
          },
          {
            id: 273,
            category: 'General Trivia',
            level: 'Easy',
            text: 'What is the powerhouse of the cell?',
            options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Endoplasmic reticulum'],
            correctAnswer: 'Mitochondria',
          },
          {
            id: 274,
            category: 'General Trivia',
            level: 'Easy',
            text: 'What is the largest mammal on Earth?',
            options: ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'],
            correctAnswer: 'Blue whale',
          },
          {
            id: 275,
            category: 'General Trivia',
            level: 'Easy',
            text: 'Which gas do plants absorb from the atmosphere?',
            options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
            correctAnswer: 'Carbon dioxide',
          },
          {
            id: 276,
            category: 'General Trivia',
            level: 'Easy',
            text: 'What is the Earth’s primary source of energy?',
            options: ['Wind', 'Coal', 'Sun', 'Natural gas'],
            correctAnswer: 'Sun',
          },
          {
            id: 277,
            category: 'General Trivia',
            level: 'Easy',
            text: 'What is the smallest bone in the human body?',
            options: ['Femur', 'Radius', 'Cochlea', 'Tibia'],
            correctAnswer: 'Cochlea',
          },
          {
            id: 278,
            category: 'General Trivia',
            level: 'Easy',
            text: 'Which gas do plants release during photosynthesis?',
            options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
            correctAnswer: 'Oxygen',
          },
          {
            id: 279,
            category: 'General Trivia',
            level: 'Easy',
            text: 'What is the freezing point of water in Celsius?',
            options: ['-10°C', '0°C', '10°C', '20°C'],
            correctAnswer: '0°C',
          },
          {
            id: 280,
            category: 'General Trivia',
            level: 'Medium',
            text: 'Which element is essential for the formation of bones in the human body?',
            options: ['Calcium', 'Iron', 'Sodium', 'Potassium'],
            correctAnswer: 'Calcium',
          },
          {
            id: 281,
            category: 'General Trivia',
            level: 'Medium',
            text: 'What is the process by which plants make their own food?',
            options: ['Photosynthesis', 'Respiration', 'Transpiration', 'Fermentation'],
            correctAnswer: 'Photosynthesis',
          },
          {
            id: 282,
            category: 'General Trivia',
            level: 'Medium',
            text: 'What is the temperature at which all molecular motion ceases?',
            options: ['-273.15°C', '-200°C', '-100°C', '0°C'],
            correctAnswer: '-273.15°C',
          },
          {
            id: 283,
            category: 'General Trivia',
            level: 'Medium',
            text: 'Who developed the theory of general relativity?',
            options: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Galileo Galilei'],
            correctAnswer: 'Albert Einstein',
          },
          {
            id: 284,
            category: 'General Trivia',
            level: 'Medium',
            text: 'What is the unit of electrical resistance?',
            options: ['Ohm', 'Ampere', 'Volt', 'Watt'],
            correctAnswer: 'Ohm',
          },
          {
            id: 285,
            category: 'General Trivia',
            level: 'Medium',
            text: 'Which gas makes up the majority of the Earth\'s atmosphere?',
            options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
            correctAnswer: 'Nitrogen',
          },
          {
            id: 286,
            category: 'General Trivia',
            level: 'Medium',
            text: 'Which force holds the nucleus of an atom together?',
            options: ['Electromagnetic force', 'Gravity', 'Nuclear force', 'Friction'],
            correctAnswer: 'Nuclear force',
          },
          {
            id: 287,
            category: 'General Trivia',
            level: 'Medium',
            text: 'What is the largest organ in the human body?',
            options: ['Heart', 'Lungs', 'Skin', 'Liver'],
            correctAnswer: 'Skin',
          },
          {
            id: 420,
            category: 'General Trivia',
            level: 'Hard',
            text: 'What is the speed of light in a vacuum?',
            options: ['299,792 km/s', '150,000 km/s', '449,234 km/s', '200,000 km/s'],
            correctAnswer: '299,792 km/s',
          },
          {
            id: 421,
            category: 'General Trivia',
            level: 'Hard',
            text: 'In chemistry, what does the term "pH" measure?',
            options: ['Pressure of Hydrogen', 'Potential of Hydrogen', 'Purity of Hydrocarbon', 'Power of Heat'],
            correctAnswer: 'Potential of Hydrogen',
          },
          {
            id: 422,
            category: 'General Trivia',
            level: 'Hard',
            text: 'What is the smallest particle of an element that retains its chemical properties?',
            options: ['Atom', 'Molecule', 'Cell', 'Electron'],
            correctAnswer: 'Atom',
          },
          {
            id: 423,
            category: 'General Trivia',
            level: 'Hard',
            text: 'Who developed the theory of general relativity?',
            options: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Galileo Galilei'],
            correctAnswer: 'Albert Einstein',
          },
          {
            id: 424,
            category: 'General Trivia',
            level: 'Hard',
            text: 'What is the unit of electrical resistance?',
            options: ['Ohm', 'Ampere', 'Volt', 'Watt'],
            correctAnswer: 'Ohm',
          },
          {
            id: 425,
            category: 'General Trivia',
            level: 'Hard',
            text: 'Which gas makes up the majority of the Earth\'s atmosphere?',
            options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
            correctAnswer: 'Nitrogen',
          },
          {
            id: 426,
            category: 'General Trivia',
            level: 'Hard',
            text: 'What is the process by which a cell divides into two daughter cells?',
            options: ['Mitosis', 'Meiosis', 'Fission', 'Budding'],
            correctAnswer: 'Mitosis',
          },
          {
            id: 427,
            category: 'General Trivia',
            level: 'Hard',
            text: 'What is the temperature at which all molecular motion ceases?',
            options: ['-273.15°C', '-200°C', '-100°C', '0°C'],
            correctAnswer: '-273.15°C',
          }
      ];

    let newQuestions = questions;
    if (level === "easy") {
        newQuestions = questions.filter((question) => question.level === 'Easy');
    } else if (level === "medium") {
        newQuestions = questions.filter((question) => question.level === 'Medium');
    } else if (level === "hard") {
        newQuestions = questions.filter((question) => question.level === 'Hard');
    } else if (category === "science") {
        newQuestions = questions.filter((question) => question.category === 'Science');
    } else if (category === "popCulture") {
        newQuestions = questions.filter((question) => question.category === 'Pop Culture');
    } else if (category === "history") {
        newQuestions = questions.filter((question) => question.category === 'History');
    } else if (category === "technology") {
        newQuestions = questions.filter((question) => question.category === 'Technology');
    } else if (category === "art") {
        newQuestions = questions.filter((question) => question.category === 'Art');
    } else if (category === "sports") {
        newQuestions = questions.filter((question) => question.category === 'Sports');
    } else if (category === "cuisine") {
        newQuestions = questions.filter((question) => question.category === 'Cuisine');
    } else if (category === "literature") {
        newQuestions = questions.filter((question) => question.category === 'Literature');
    } else if (category === "movies") {
        newQuestions = questions.filter((question) => question.category === 'Movies & TV');
    } else if (category === "music") {
        newQuestions = questions.filter((question) => question.category === 'Music');
    } else if (category === "general") {
        newQuestions = questions.filter((question) => question.category === 'General Trivia');
    } else if (category === "geography") {
        newQuestions = questions.filter((question) => question.category === 'Geography');
    }

    let randomIndex = Math.floor(Math.random() * newQuestions.length);
    let currQ = newQuestions[randomIndex].text;
    let answers = newQuestions[randomIndex].options;
    let correct = newQuestions[randomIndex].correctAnswer;

    const handleAnswerClick = (selectedAnswer) => {
        if (selectedAnswer === correct) {
            setPoints(prevPoints => {
                const updatedPoints = [...prevPoints];
                updatedPoints[currentTeam] += 1;
                return updatedPoints;
              });
            handleSetStatus("Correct!");
        } else {
            handleSetStatus("Wrong :(");
        }
        setCurrentPage("points");
    };
    
    return (
        <div className="teamsContainer">
            <div style={{ background: "black", width: "100vw", height: "100vh", color: "white", alignContent: "center"}}>
                <b style={{alignItems: "center", color: "white", fontFamily: "monospace", fontSize: "4vw"}}>{currQ}</b>
                <div style={{height: "8vh"}}></div>
                <div style={{marginLeft: "8vw"}}>
                    <text style={{background: "#28fc81", marginRight: "6vw", fontSize: "2.8vw"}} className="teamsChoice" 
                    onClick={() => handleAnswerClick(answers[0])}><b>{answers[0]}</b></text>
                    <text style={{background: "#ff6bee", marginRight: "6vw", fontSize: "2.8vw"}} className="teamsChoice" 
                    onClick={() => handleAnswerClick(answers[1])}><b>{answers[1]}</b></text>
                </div>
                <div style={{marginTop: "18vh", marginLeft: "8vw"}}>
                    <text style={{background: "#c66bff", marginRight: "6vw", fontSize: "2.8vw"}} className="teamsChoice" 
                    onClick={() => handleAnswerClick(answers[2])}><b>{answers[2]}</b></text>
                    <text style={{background: "#44d8fc", marginRight: "6vw", fontSize: "2.8vw"}} className="teamsChoice" 
                    onClick={() => handleAnswerClick(answers[3])}><b>{answers[3]}</b></text>
                </div>
                <div style={{marginTop: "10vh", paddingLeft: "10vh", paddingRight: "10vh"}}>
                    <div style={{background: "#44d8fc", fontSize: "3vw", color: "black"}} onClick={() => handleSetPage("main")}><b>Main Menu</b></div>
                </div>
            </div>
        </div>
    );
};